# create a makefile variable named CC for your C/C++ compiler (es gcc, c++, ... )

# create a makefile variable named OPT with your favorite C flags (at least with -std=c99 -O3)

#create the target 'bin/get_time_test' which needs 'get_time_test.c' and 'my_time_lib.o', generate the folder 'bin' and compile get_time_test.c using CC and OPT

#create the target 'clean' which recursively remove the folders 'bin' and 'obj'

